server:
  port: 1000

app:
  api-prefix: /api/v1

logging:
  level:
    '[root]': WARN
    '[com.thaca.gateway]': INFO

spring:
  application:
    name: thaca-gateway

  profiles:
    include: framework

  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${APPLICATION_ROUTES_AUTH_SERVICE:http://localhost:1001}
              predicates:
                - Path=${app.api-prefix}/auth/**
              filters:
                - StripPrefix=2

            - id: cms-service
              uri: ${APPLICATION_ROUTES_CMS_SERVICE:http://localhost:1002}
              predicates:
                - Path=${app.api-prefix}/cms/**
              filters:
                - StripPrefix=2

            - id: notification-service
              uri: ${APPLICATION_ROUTES_NOTIFICATION_SERVICE:http://localhost:1003}
              predicates:
                - Path=${app.api-prefix}/notification/**
              filters:
                - StripPrefix=2
