server:
  port: 1000

app:
  api-prefix: /api/v1

application:
  routes:
    auth-service: ${AUTH_SERVICE_URL:http://localhost:1001}

logging:
  level:
    '[root]': WARN
    '[com.leaf]': INFO
    '[org.springframework]': WARN

spring:
  application:
    name: gateway

  profiles:
    include: framework

  output:
    ansi:
      enabled: always

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:1001}
              predicates:
                - Path=${app.api-prefix}/auth/**, ${app.api-prefix}/cms/**, ${app.api-prefix}/admin/**
              filters:
                - RewritePath=${app.api-prefix}/(?<segment>.*), /api/$\{segment}

            - id: file-service
              uri: lb://file
              predicates:
                - Path=${app.api-prefix}/files/**
              filters:
                - StripPrefix=2

            - id: profile-service
              uri: lb://user-profile
              predicates:
                - Path=${app.api-prefix}/user-profile/**
              filters:
                - StripPrefix=2

            - id: notification-service
              uri: lb://notification
              predicates:
                - Path=${app.api-prefix}/notifications/**
              filters:
                - StripPrefix=2

            - id: graphql-bff
              uri: lb://graphql-bff
              predicates:
                - Path=${app.api-prefix}/graphql/**
              filters:
                - StripPrefix=2

            - id: websocket-service-ws
              uri: lb:ws://websocket-service
              predicates:
                - Path=/ws/**
              filters:
                - SetPath=/ws

            - id: websocket-service-http
              uri: lb://websocket-service
              predicates:
                - Path=${app.api-prefix}/presence/**
              filters:
                - StripPrefix=2
