server:
  port: 1003

  servlet:
    context-path:

spring:
  application:
    name: thaca-notification

  profiles:
    active: core
    include: blocking,dev

  output:
    ansi:
      enabled: always

  liquibase:
    enabled: true
    change-log: liquibase/changelog-master.xml
    default-schema: notification
    liquibase-schema: notification

  messages:
    basename: i18n/messages
    encoding: UTF-8

app:
  base-url: http://localhost:1003
