logging:
  level:
    '[root]': WARN
    '[com.thaca]': INFO
    '[org.springframework]': WARN

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/thaca?options=-c%20timezone=UTC}
    username: ${POSTGRES_USERNAME:root}
    password: ${POSTGRES_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS cms

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_NOTIFICATION_CONSUMER_GROUP_ID:thaca-notification-group}
