server:
  port: 1003

  servlet:
    context-path:

spring:
  application:
    name: thaca-notification

  profiles:
    active: dev
    include: core,blocking

  output:
    ansi:
      enabled: always
